---
- name: Show hidden files by default
  shell: |
    defaults write com.apple.finder AppleShowAllFiles -bool true

- name: Show all filename extensions
  shell: |
    defaults write NSGlobalDomain AppleShowAllExtensions -bool true

- name: Show status bar
  shell: |
    defaults write com.apple.finder ShowStatusBar -bool true

- name: Show path bar
  shell: |
    defaults write com.apple.finder ShowPathbar -bool true

- name: When performing a search, search the current folder by default
  shell: |
    defaults write com.apple.finder FXDefaultSearchScope -string "SCcf"

- name: Disable the warning when changing a file extension
  shell: |
    defaults write com.apple.finder FXEnableExtensionChangeWarning -bool false

- name: Avoid creating .DS_Store files on network volumes
  shell: |
    defaults write com.apple.desktopservices DSDontWriteNetworkStores -bool true

- name: Enable snap-to-grid for icons on the desktop and in other icon views
  shell: |
    /usr/libexec/PlistBuddy -c "Set :DesktopViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :FK_StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist
    /usr/libexec/PlistBuddy -c "Set :StandardViewSettings:IconViewSettings:arrangeBy grid" ~/Library/Preferences/com.apple.finder.plist

- name: Use list view in all Finder windows by default
  shell: |
    defaults write com.apple.finder FXPreferredViewStyle -string "Nlsv"